---
- name: Install dependencies for awscli
  yum:
    name: "python3-pip"
    state: latest
    update_cache: yes
- name: Install awscli with pip3
  pip:
    name: "awscli"
    executable: pip3 
#- name: Install boto
 # pip:
  #  name: ["boto3", "botocore"]
   # executable: pip3
   # extra_args: "--user"

- name: installing CloudWatch
  yum: 
    name: amazon-cloudwatch-agent 
    state: latest
  notify: Start CloudWatch
